# All video-level tasks joint training (32 GPU training)
# main setting (ConvNext-Large video-level joint training)
_BASE_: "../video_joint_convnext_large.yaml" # all video tasks joint training
DATASETS:
  TEST: ("bdd_box_track_val", ) # "bdd_seg_track_val"
INPUT:
  MIN_SIZE_TEST: 800